project:
  type: website
  output-dir: docs

website:
  title: "Kaynath's Website"
  navbar:
    left:
      - href: index.qmd
        text: Research Project
      - href: analysis.qmd
        text: Voter Simulation
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
editor: visual



